image: Visual Studio 2019
skip_commits:
  message: /doco|Merge pull request.*/
build_script:
- cmd: dotnet build --configuration Release
test:
  assemblies:
    - '**\*Tests.dll'
artifacts:
- path: nugets\**\*.nupkg